### ISSUE TITLE
Upgrade from 4.7 to 5.6.5-1 with issues

### ISSUE THREAD

**Issue by Will2knz** [dleidert/openmediavault-upgrade#37]
Hey all

Have just updated my omv from 4.7 to 5.6.5-1. After rebooting the system and logging back into the Ui it came up with "The configuration has been changed. You must apply the changes in order for them to take effect.". So i try to apply the changers with no luck it keeps come up with a "An error has occurred" please find the details below. Any help with fixing this issue will appreciated

Screenshots below

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color avahi 2>&1' with exit code '1': Destiny.flat.intranet: Data failed to compile:
---------- Rendering SLS 'base:omv.deploy.avahi.services.nfs' failed: Jinja error: shares: The value ' ' is not an object.
Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl output = template.render(**decoded_context) File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render return original_render(self, *args, **kwargs) File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise raise value.with_traceback(tb) File "<template>", line 21, in top-level template code File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 438, in call return __context.call(__obj, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__ return self.loader.run(run_func, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as return _func_or_method(*args, **kwargs) File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get objs = db.get(id_, identifier) File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get query.execute() File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 726, in execute self._response = self._elements_to_object(elements) File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 487, in _elements_to_object result.validate() File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 236, in validate self.model.validate(self.get_dict()) File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 202, in validate self.schema.validate(data) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 175, in validate self._validate_type(value, schema, name) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 229, in _validate_type raise last_exception File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 200, in _validate_type self._validate_object(value, schema, name) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 305, in _validate_object self._check_properties(value, schema, name) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 519, in _check_properties self._validate_type(value[propk], propv, path) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 229, in _validate_type raise last_exception File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 200, in _validate_type self._validate_object(value, schema, name) File "/usr/lib/python3/dist-packages/openmediavault/json/schema.py", line 303, in _validate_object % ("NULL" if (value is None) else str(value)),
openmediavault.json.schema.SchemaValidationException: shares: The value ' ' is not an object.

; line 21

---
[...]
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set nfs_export_dir = salt['pillar.get']('default:OMV_NFSD_EXPORT_DIR', '/export') %}
{% set nfs_config = salt['omv_conf.get']('conf.service.nfs') %} <======================
{% set nfs_zeroconf_enabled = salt['pillar.get']('default:OMV_NFSD_ZEROCONF_ENABLED', 1) %}
{% set nfs_zeroconf_name = salt['pillar.get']('default:OMV_NFSD_ZEROCONF_NAME', '%h - NFS') %}

remove_avahi_service_nfs: module.run:
[...]
--- in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusse...', '/tmp/bgoutput4m...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}[](url)

![1](https://user-images.githubusercontent.com/38000012/116808120-44eb3080-ab8b-11eb-91c9-9de7e86c47a0.JPG)
![2](https://user-images.githubusercontent.com/38000012/116808131-4f0d2f00-ab8b-11eb-9b1f-e60046e96039.JPG)
![3](https://user-images.githubusercontent.com/38000012/116808142-57656a00-ab8b-11eb-9fe9-be3c51e8ea36.JPG)

**Comment by godfuture** [comment]
Maybe a dump question...have you executed the migration scripts? Or do you think this is the right place for omv issues?

You can guess why I am asking...omv issues are not handled here. If you have executed the migration scripts, could you provide migration logs?

Thx

PS: I am not the author of the scripts, but in deep respect of his work trying to help out. Please consider.

**Comment by Will2knz** [comment]
Yep i did executed the migration scripts.  ovm did upgrade to 5.6.5-1 (USul) but after rebooting the system i have run into this issue.

Thanks

Here is the migration log 


[omv_release_upgrade_to_buster.2021-04-29-222507.log](https://github.com/dleidert/openmediavault-upgrade/files/6426098/omv_release_upgrade_to_buster.2021-04-29-222507.log)

**Comment by godfuture** [comment]
I am not developing these scripts, but to me your migration log seems ok, because you successfully reached:
`Successfully upgraded to 5.0 (Usul) ..."`

I would go to omv forum with the stacktrace that you encounter while applying the changes. It seems there is a problem at:
`/usr/share/php/openmediavault/system/process.inc:195`
Maybe together with your settings after upgrade, they will be able to help you out. 

This is at least what I would do...

**Comment by godfuture** [comment]
One thing comes to my mind: did you follow this guide line before executing the scripts? If not, do you have a backup to go back disable all services and retry to execute the migration script?

> Preparations
> 
> I recommend to stop all services openmediavault provides, including Samba, Rsync, Nfs, etc. except SSH. Just log into the GUI and disable these services. The rationale is to prevent your users from using these services while the upgrade is running: Services might not be reliable during the upgrade.

**Comment by Will2knz** [comment]
No i didn't stop all services as there was no users using the server at the time of upgrade. When i upgrade from 3 to 4 i didn't stop the services either and was able to update with no issues.
No i didn't create a backup. I know i should have.

**Comment by Will2knz** [comment]
> 
> 
> I am not developing these scripts, but to me your migration log seems ok, because you successfully reached:
> `Successfully upgraded to 5.0 (Usul) ..."`
> 
> I would go to omv forum with the stacktrace that you encounter while applying the changes. It seems there is a problem at:
> `/usr/share/php/openmediavault/system/process.inc:195`
> Maybe together with your settings after upgrade, they will be able to help you out.
> 
> This is at least what I would do...

I have posted this on the ovm forums  too last weekend and havn't had any reply's yet

**Comment by godfuture** [comment]
> No i didn't create a backup. I know i should have.

It is really not hard and should always be considered -> clonezilla on USB drive. Disk to image including MBR/GPT table. I have created a Veracrypt drive to store data on external disk for Linux and Windows use. But you can also let clonezilla do the encryption if needed. So many options. Take a look.

Example: I restored this clonezilla disk image onto a Virtualbox disk by booting clonezilla inside a Virtualbox machine. You can then create a snapshot before upgrade and test it as many times as you need to make it work.

> openmediavault.json.schema.SchemaValidationException: shares: The value ' ' is not an object.

It looks like there is a problematic share. I would check the shares including SMB/shared folder setup.

**Comment by mi-hol** [comment]
@Will2knz is the issue still open or was it resolved via OMV forum posts in https://forum.openmediavault.org/index.php?thread/37269-upgrade-scripts-for-non-interactive-major-release-upgrades-2-3-3-4-4-5/&pageNo=1 ?

**Comment by Will2knz** [comment]
@mi-hol  Yes the issue is still open and it wasn't  resolved on the OMV forum either. No  has yet reply to my post: [https://forum.openmediavault.org/index.php?thread/37269-upgrade-scripts-for-non-interactive-major-release-upgrades-2-3-3-4-4-5/&postID=274216#post274216](url)

**Comment by mi-hol** [comment]
please close issue and lets continue on OMV forum.
I replied in https://forum.openmediavault.org/index.php?thread/37269-upgrade-scripts-for-non-interactive-major-release-upgrades-2-3-3-4-4-5/&postID=279548#post279548
