### ISSUE TITLE
python TypeError on upgrade from 4 to 5

### ISSUE THREAD

**Issue by mkaut** [dleidert/openmediavault-upgrade#43]
I tried to upgrade from 4 to 5 using the instructions from [https://github.com/dleidert/openmediavault-upgrade/tree/4], but the script failed with a python TypeError. The end of the output was:

```bash
 delete mode 120000 rc0.d/K03mysql
 delete mode 120000 rc1.d/K03mysql
 delete mode 120000 rc2.d/S03mysql
 delete mode 120000 rc3.d/S03mysql
 delete mode 120000 rc4.d/S03mysql
 delete mode 120000 rc5.d/S03mysql
 delete mode 120000 rc6.d/K03mysql
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f56f1a73598>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f56f1a73598>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I also attach the whole log file: [omv_release_upgrade_to_buster.2021-08-23-110755.log](https://github.com/dleidert/openmediavault-upgrade/files/7030723/omv_release_upgrade_to_buster.2021-08-23-110755.log)

Any idea how to fix this? And is it safe to (try to) use OMV in the meantime?

**Comment by mi-hol** [comment]
Its much better to have this conversation on OMV forum.
https://forum.openmediavault.org/index.php?thread/39933-trying-to-update-error/&postID=280853&highlight=bintray#post280853 has the answer
